services:
  multi4channels-qsv:
    image: ghcr.io/rice9797/multi4channels-qsv:${TAG}
    container_name: multi4channels-qsv
    ports:
      - ${HOST_PORT}:${WEB_PAGE_PORT}
      - ${HOST_RTP}:${RTP_PORT}/udp
    devices:
      - /dev/dri:/dev/dri
    environment:
      - CDVR_HOST=${CDVR_HOST}
      - CDVR_PORT=${CDVR_PORT}
      - CDVR_CHNLNUM=${CDVR_CHNLNUM}
      - OUTPUT_FPS=${OUTPUT_FPS}
      - RTP_HOST=${RTP_HOST}
      - RTP_PORT=${RTP_PORT}
      - WEB_PAGE_PORT=${WEB_PAGE_PORT}
    volumes:
      - multi4channels-qsv:/app/data
      - ./app/photos:/app/photos
    restart: unless-stopped
volumes:
  multi4channels-qsv:
    name: ${HOST_VOLUME}
